export const Data = [
  {
    bananas: 200,
    lastDayPlayed: '2018-11-22',
    longestStreak: 1,
    name: 'Rica Ella Francisco',
    stars: 6,
    subscribed: false,
    uid: '00D1LA8puAa1GINkVpfgC1TmO0m1',
  },
  {
    bananas: 0,
    lastDayPlayed: '2017-11-01',
    longestStreak: 0,
    name: 'Adh Fuoo',
    stars: 4,
    subscribed: false,
    uid: 'x8RNvUgv5pZqDVatEXb2aYgSflq1',
  },
  {
    bananas: 150,
    lastDayPlayed: '2018-10-17',
    longestStreak: 1,
    name: 'Jayne Su YueHe',
    stars: 4,
    subscribed: false,
    uid: 'ylL3XqPOlycHiPBuf1uXHlgZzEr2',
  },
  {
    bananas: 0,
    lastDayPlayed: '2017-11-01',
    longestStreak: 0,
    name: 'Yo Yo Chou',
    stars: 4,
    subscribed: false,
    uid: 'ylsPzJdfKggHuBVcqHVYxzVRdtJ2',
  },
  {
    bananas: 0,
    lastDayPlayed: '2017-11-01',
    longestStreak: 0,
    name: 'Toke Chen',
    stars: 4,
    subscribed: false,
    uid: 'ylwtBuIr70fEIxcCE80fSRRo7np2',
  },
  {
    bananas: 0,
    lastDayPlayed: '2017-11-01',
    longestStreak: 0,
    name: '王連辟',
    stars: 5,
    subscribed: false,
    uid: 'ymAf3Zs3MCe0zwjQnATm2B9LmeY2',
  },
  {
    bananas: 1100,
    lastDayPlayed: '2018-08-04',
    longestStreak: 1,
    name: 'Bernard Andy Eugenio Gulla',
    stars: 9,
    subscribed: false,
    uid: 'ymXlQBolGjc664PfpwjeMG3slbD3',
  },
  {
    bananas: 750,
    lastDayPlayed: '2018-12-10',
    longestStreak: 2,
    name: 'Mark Wong',
    stars: 7,
    subscribed: false,
    uid: 'ymddj0GvbKSeNTC3zDa6eYqjZnY2',
  },
  {
    bananas: 200,
    lastDayPlayed: '2018-06-17',
    longestStreak: 1,
    name: 'amirul hariz',
    stars: 5,
    subscribed: false,
    uid: 'ymi5YolrBOTmzPJs1ZEvAxWVzx92',
  },
  {
    bananas: 0,
    lastDayPlayed: '2017-11-01',
    longestStreak: 0,
    name: 'Nur Gümüş',
    stars: 5,
    subscribed: false,
    uid: 'ymonOSLRONZxm99JFaPcbUoZSOF3',
  },
  {
    bananas: 900,
    lastDayPlayed: '2018-05-09',
    longestStreak: 2,
    name: 'Victoria Vang',
    stars: 8,
    subscribed: false,
    uid: 'yn8Jn7LPoCcL3e6KZtGx3RmzDB63',
  },
  {
    bananas: 2150,
    lastDayPlayed: '2018-10-11',
    longestStreak: 2,
    name: 'Iolanda Rodrigues',
    stars: 15,
    subscribed: false,
    uid: 'ynGq0tckUyTBHFiB0c6v2Y2NxGH3',
  },
  {
    bananas: 550,
    lastDayPlayed: '2018-12-05',
    longestStreak: 1,
    name: 'diana smith',
    stars: 6,
    subscribed: false,
    uid: 'ynXlyqthAfTrFbK8M4iQFFZTkYp2',
  },
  {
    bananas: 0,
    lastDayPlayed: '2017-11-01',
    longestStreak: 0,
    name: 'Qiao Yee',
    stars: 5,
    subscribed: false,
    uid: 'yniH9BMgoUYDFV3oNzBoKLq9BYj1',
  },
  {
    bananas: 200,
    lastDayPlayed: '2018-08-13',
    longestStreak: 1,
    name: 'Daniel Horn',
    stars: 6,
    subscribed: false,
    uid: 'yniTP0KsvfRDuw8weRArLiUDLR13',
  },
  {
    bananas: 0,
    lastDayPlayed: '2017-11-01',
    longestStreak: 0,
    name: '',
    stars: 5,
    subscribed: false,
    uid: 'ynp3NHnzBBYGf0WWiOdMDug0bXZ2',
  },
  {
    bananas: 2100,
    lastDayPlayed: '2018-05-12',
    longestStreak: 2,
    name: 'laila',
    stars: 14,
    subscribed: false,
    uid: 'yo4XFheX0DRGXLWsDMwUwvPUvN23',
  },
  {
    bananas: 150,
    lastDayPlayed: '2019-02-06',
    longestStreak: 1,
    name: 'Emma-Lee Crothers',
    stars: 5,
    subscribed: false,
    uid: 'yo5Sj0tkgFeTAmfU72ankN9rMwO2',
  },
  {
    bananas: 0,
    lastDayPlayed: '2017-11-01',
    longestStreak: 0,
    name: 'Ocelotl Kanpol',
    stars: 5,
    subscribed: false,
    uid: 'yoDHUejMeshN1bOw9Bq671vMaph2',
  },
  {
    bananas: 0,
    lastDayPlayed: '2017-11-01',
    longestStreak: 0,
    name: '박성재',
    stars: 5,
    subscribed: false,
    uid: 'yoGaR3ZFBhbzquGaxpj0kYSWZ3E3',
  },
  {
    bananas: 0,
    lastDayPlayed: '2017-11-01',
    longestStreak: 0,
    name: 'Victoria Lea',
    stars: 5,
    subscribed: false,
    uid: 'yoSIZR2qFWPHCxezohG6A6j1Z0A3',
  },
  {
    bananas: 1700,
    lastDayPlayed: '2018-12-06',
    longestStreak: 1,
    name: 'Abhishek',
    stars: 12,
    subscribed: false,
    uid: 'yoSPvRbIpNcrIC7UyvRvWjvaA4R2',
  },
];
