// export const data = [
//   {
//     type: 'all',
//     img: require('../src/images/jeans.png'),
//     name: 'blue Jeans',
//     price: '$39',
//   },
//   {
//     type: 'all',
//     img: require('../src/images/jeans.png'),
//     name: 'blue Jeans',
//     price: '$414',
//   },
//   {
//     type: 'jeans',
//     img: require('../src/images/kurta.png'),
//     name: 'jaguar',
//     price: '$500',
//   },
//   {
//     type: 'jeans',
//     img: require('../src/images/kurta.png'),
//     name: 'jaguar',
//     price: '$500',
//   },
//   {
//     type: 'pant',
//     img: require('../src/images/jeans.png'),
//     name: 'polo white',
//     price: '$500',
//   },
//   {
//     type: 'pant',
//     img: require('../src/images/polo.png'),
//     name: 'polo red',
//     price: '$500',
//   },
//   {
//     type: 'kurta',
//     img: require('../src/images/kurta.png'),
//     name: 'white kurta',
//     price: '$500',
//   },
//   {
//     type: 'pajama',
//     img: require('../src/images/jeans.png'),
//     name: 'white pajama',
//     price: '$500',
//   },
//   {
//     type: 'pajama',
//     img: require('../src/images/jeans.png'),
//     name: 'white pajama',
//     price: '$500',
//   },
//   {
//     type: 'pajama',
//     img: require('../src/images/jeans.png'),
//     name: 'white pajama',
//     price: '$500',
//   },
//   {
//     type: 'jeans',
//     img: require('../src/images/kurta.png'),
//     name: 'jaguar',
//     price: '$500',
//   },
//   {
//     type: 'all',
//     img: require('../src/images/jeans.png'),
//     name: 'blue Jeans',
//     price: '$414',
//   },
//   {
//     type: 'jeans',
//     img: require('../src/images/kurta.png'),
//     name: 'jaguar',
//     price: '$500',
//   },
// ];
